/**
 * Copyright (c) MuleSoft, Inc.  All rights reserved.  http://www.mulesoft.com
 * The software in this package is published under the terms of the CPAL v1.0
 * license, a copy of which has been included with this distribution in the
 * LICENSE.txt file.
 **/
        
/**
 * This file was automatically generated by the Mule Development Kit
 */
package mx.maleficarum;

import org.mule.api.annotations.Connector;
import org.mule.api.annotations.Configurable;
import org.mule.api.annotations.Processor;

import com.hazelcast.client.HazelcastClient;
import com.hazelcast.client.config.ClientConfig;
import com.hazelcast.core.HazelcastInstance;


/**
 * Cloud Connector
 *
 * @author MuleSoft, Inc.
 */
@Connector(name="hazelcast", schemaVersion="1.0-SNAPSHOT")
public class HazelcastConnector {
	
	private ClientConfig config = null;
	private HazelcastInstance instance = null;

	public HazelcastConnector() {
 		config = new ClientConfig();
	}
	
    @Configurable
    private String clusterAddress;

    public void setClusterAddress(String address) {
    	this.clusterAddress = address;
    	if(instance == null) {
    		config.addAddress("127.0.0.1:5701");
            instance = HazelcastClient.newHazelcastClient(config);    		
    	}
    }

    public String getClusterAddress() {
    	return clusterAddress;
    }
    
    @Processor
    public String put(String content) {

        return content;
    }

    @Processor
    public String get(String content) {

        return content;
    }

}
